### ISSUE TITLE
Firewall-Rules Guest In does not work

### ISSUE THREAD

**Issue by Rokk001** [11notes/docker-unifi#18]
Hi guys
I've upgraded from unifi-controller to unifi-controller-reborn (unraid-amd64-8.2.93) and restore from backup.
The Traffic-Rules are all imported. 

![image](https://github.com/11notes/docker-unifi/assets/6574988/255790e3-c3b8-4779-a252-d2e5847b2a3e)

My privileged devices connected over Guests WLAN cannot connect to other networks. 
This had worked fine with unifi-controller.

Regards

**Comment by bmartino1** [comment]
I can't reproduce. Is the wifi devices Pre authorized?
https://community.ui.com/questions/Allowing-1-device-accessable-on-LAN-on-guest-network/eb8a515c-9f09-4c6e-bcc0-6e1e749a6863

This sounds more like a nat /port forwarding problem.

The controller won't pull up lan or firewall rules without a unifi device that has the capability.
In essence, we ned more information.

What is a brief network diagram, xyz conneted to xyz?

Modem > ?firewall/router(dhcp server) > Box running Unifi Controller application
??firewall/router(dhcp server) > (what unifi netwrok switch)
?firewall/router(dhcp server) >> (What Unifi wifi Access point)
xyz guest device

From the picture the rule may exist but might not be applied, what happens if you delete the rule and recreate it?

**Comment by Rokk001** [comment]
Hello guys

I have a UX Gateway and no matter what Firewall Rules I define, Reborn ignores everything.
I need a FW Rule to allow my IoT devices connecting to my docker in another VLAN. This works perfectly with the container unifi-controller.

Regards

**Comment by bmartino1** [comment]
I have a UX as well and currently run a USG.

What firewall rule are you trying to apply as you need to use nat rules...

https://help.ui.com/hc/en-us/articles/5546542486551-UniFi-Gateway-Traffic-and-Firewall-Rules

You may not have a full nat firewall rule setup...

Example for allowing ping on the wan:

![image](https://github.com/user-attachments/assets/5edce54d-fc38-493c-b132-83ca30fa8bb4)

I require more than 1 rule. So what are you trying to nat or firewall rule.

**Comment by Rokk001** [comment]
I want to connect my TV (IoT VLAN) with my Emby Container on my NAS (Default VLAN).
I created a SImple rule:
![image](https://github.com/user-attachments/assets/fe181608-7de4-474a-8922-eda20c93009f)

**Comment by bmartino1** [comment]
Ok since these are VLAN, we will need to make a min of 3 nat rule to accomplish this.

This is better asked on the unifi forum...
Review:
Traffic Rule to Allow Inter-VLAN Routing
https://community.ui.com/questions/Traffic-Rule-to-Allow-Inter-VLAN-Routing/d20d4747-ffb8-4670-9878-271fe522ad24
and
https://community.ui.com/questions/Firewall-Rule-to-allow-devices-on-different-VLANS-to-communicate/c68cbeec-581b-4fa3-a167-f4bf5c7051bf

other video links with some helpful info to accomplish this:

https://www.youtube.com/watch?v=yqDhs3Lg-gY

https://www.youtube.com/watch?v=bwecgBdWgeQ

https://www.youtube.com/watch?v=v0B2IDEfnjA

**Comment by Rokk001** [comment]
I fixed it. 
I don't know what the issue was, but after disabling Intrusion Detection and Prevention and enable it again, all my rules are working. Magic.

**Comment by Rokk001** [comment]
Thanks for your support
